
name: Build VS Code extension

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install Dependencies
        run: |
          sudo apt install golang-go npm upx-ucl
          go get github.com/gorilla/mux
          sudo npm install -g vsce

      - name: Build Linux debug server
        run: |
          go build -o VSCode_Extension/DebugServerLinux TestServer/*.go
          upx -9 VSCode_Extension/DebugServerLinux


      - name: Build Windows debug server
        run: |
          GOOS="windows" go build -o VSCode_Extension/DebugServer.exe TestServer/*.go
          upx -9 VSCode_Extension/DebugServer.exe

      - name: Copy MTA Resource
        run: |
          mkdir VSCode_Extension/debugger_mta_resource
          cp -r LuaLibrary/debugger/* VSCode_Extension/debugger_mta_resource

      - name: Load Node modules
        run: |
          cd VSCode_Extension
          npm install

      - name: Build VS Code extension
        run: |
          cd VSCode_Extension
          vsce package -o mtatd.vsix

      - uses: actions/upload-artifact@v2
        with:
          name: VSCode Extension
          path: VSCode_Extension/mtatd.vsix